version: '3'

services:
  web:
    build: .
    command: sh -c "uvicorn main:app --reload --port=8080 --host=0.0.0.0"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=./application_default_credentials.json
    env_file:
      - .env
    ports:
      - 8080:8080




